CREATE USER 'ayrema'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'ayrema'@'localhost';
CREATE USER 'cabaan'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'cabaan'@'localhost';
CREATE USER 'camoan'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'camoan'@'localhost';
CREATE USER 'cepahe'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'cepahe'@'localhost';
CREATE USER 'cocrad'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'cocrad'@'localhost';
CREATE USER 'cuolan'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'cuolan'@'localhost';
CREATE USER 'fearan'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'fearan'@'localhost';
CREATE USER 'feesvi'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'feesvi'@'localhost';
CREATE USER 'frroje'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'frroje'@'localhost';
CREATE USER 'gacead'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'gacead'@'localhost';
CREATE USER 'gomaad'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'gomaad'@'localhost';
CREATE USER 'gorofr'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'gorofr'@'localhost';
CREATE USER 'lafr'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'lafr'@'localhost';
CREATE USER 'lumase'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'lumase'@'localhost';
CREATE USER 'lubrla'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'lubrla'@'localhost';
CREATE USER 'maloda'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'maloda'@'localhost';
CREATE USER 'mevepa'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'mevepa'@'localhost';
CREATE USER 'poarja'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'poarja'@'localhost';
CREATE USER 'prizal'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'prizal'@'localhost';
CREATE USER 'romaan'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'romaan'@'localhost';
CREATE USER 'ruderi'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'ruderi'@'localhost';
CREATE USER 'ruloed'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'ruloed'@'localhost';
CREATE USER 'sotean'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'sotean'@'localhost';
CREATE USER 'tahegu'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'tahegu'@'localhost';
CREATE USER 'vaabal'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'vaabal'@'localhost';
CREATE USER 'vaabal1'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'vaabal1'@'localhost';
